#!/bin/bash

script=$(mktemp)
sed "s/\$WINDOWNAME/$1/" $(dirname $0)/switch.js > $script
script_id=$(qdbus org.kde.KWin /Scripting loadScript $script)
qdbus org.kde.KWin /Scripting/Script$script_id run
qdbus org.kde.KWin /Scripting/Script$script_id stop
